server:
  port: 8083
  session:
    timeout: 100
  tomcat:
    uri-encoding: UTF-8
spring: 
  application: 
    name: rabbitmq-amqp
  
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbimq
    password: rabbimq
    


 
