server:
  port: 8080
  
spring:
  application:
    name: feign-server
#控制台彩色输出
  output:
    ansi:
      enabled: always
      
    

# 注册eureka    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
      
logging:
  level:
    com.answern.feign: DEBUG
    