server:
  port: 8082
  session:
    timeout: 100
  tomcat:
    uri-encoding: UTF-8
spring: 
  application: 
    name: config-client  
  

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbimq
    password: rabbimq 
    publisher-confirms: true
    virtual-host: /
debug: false


 
