server:
  port: 8082
  session:
    timeout: 100
  tomcat:
    uri-encoding: UTF-8

  
spring: 
  application: 
    name: config-client-foo

debug: false

#- swagger.title=标题
#- swagger.description=描述
#- swagger.version=版本
#- swagger.license=许可证
#- swagger.licenseUrl=许可证URL
#- swagger.termsOfServiceUrl=服务条款URL
#- swagger.contact.name=维护人
#- swagger.contact.url=维护人URL
#- swagger.contact.email=维护人email
#- swagger.base-package=swagger扫描的基础包，默认：全扫描
#- swagger.base-path=需要处理的基础URL规则，默认：/**
#- swagger.exclude-path=需要排除的URL规则，默认：空
#- swagger.host=文档的host信息，默认：空
swagger:
  docket:
    aa:  
      title: 这里是一个title
      description: 这里是description
      version: 1.1version
      license: Apache License, Version 2.0
      license-url: http://www.baidu.com
      terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
      contact:
        name: contactName
        url: http://www.baidu.com
        email: wem@126.com
      base-package: com.answern.config.client   # 扫描的基础包，默认：全扫描
      base-path: /**              #需要处理的基础URL规则，默认：/**
      exclude-path: /error,/ops/*  # 需要排除的URL规则，默认：空

 
    bb:  
      title: 这里是一个title22
      description: 这里是description22
      version: 1.1version22
      license: Apache License, Version 2.0
      license-url: http://www.baidu.com
      terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
      contact:
        name: contactName
        url: http://www.baidu.com
        email: wem@126.com
      base-package: com.answern.config.client   # 扫描的基础包，默认：全扫描
      base-path: /**              #需要处理的基础URL规则，默认：/**
      exclude-path: /error,/ops/*  # 需要排除的URL规则，默认：空
