spring:
  application:
    name: feign-client
  output:
    ansi:
      enabled: detect
  sleuth: 
    sampler:
      percentage: 1.0  #抽样
  zipkin:
     base-url: http://localhost:9411
     locator:
      discovery:
        enabled: true
     
    
# 注册eureka    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
