server:
  port: 7070
  session:
    timeout: 100
  tomcat:
    uri-encoding: UTF-8
spring:
  output:
    ansi:
      enabled: detect
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: rabbimq
#    password: rabbimq

eureka:
  instance:
    hostname: localhost
  client:
    region: region
    availability-zones:
      zones: ownzones
    register-with-eureka: false   # 关闭eureka客户端登记
    fetch-registry: false         # 关闭检查服务
    service-url:
      ownzones : http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      
      