server:
  port: 9411
  
spring:
  application:
    name: zipkin-server
  config:
    location: config
  profiles:
    active: banner,rabbitmq
  zipkin:
    locator:
      discovery:
        enabled: false
# 注册eureka    
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/