### Mybatis 配置
mybatis:
  config-location: classpath:config/mybatis-config.xml
   
spring: 
  mvc: 
    view: 
      prefix: /templates/
      suffix: .ftl
##pagehelper分页插件配置
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql
