server:
  port: 8081
  
spring:
  application:
    name: feign-client
#控制台彩色输出
  output:
    ansi:
      enabled: detect
# 注册eureka    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/